In [1]:
import pandas as pd
import time
from datetime import datetime
from os import path
import requests
from bs4 import BeautifulSoup

In [2]:
# Create the link (it is a better idea to constuct the especially link if you notice a specific pattern..)
link_first_part = 'https://www.atptour.com/' 
link_mid_1_part = 'en/players/roger-federer/f324/rankings-history'

url = link_first_part + link_mid_1_part
url

'https://www.atptour.com/en/players/roger-federer/f324/rankings-history'

In [3]:
# get the content from the link
response =requests.get(url, timeout=50)

# parse the content with BeautifulSoup with the html.parser method
soup = BeautifulSoup(response.content, "html.parser")

#check status code of the downloaded page
response.status_code
soup.findAll('tbody')

[<tbody>
 <tr>
 <td>
                     2019.11.11
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.11.04
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.10.28
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.10.21
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.10.14
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.10.07
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.09.30
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.09.23
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.09.16
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.09.09
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.08.26
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.08.19
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.08.12
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.08.05
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.07.29
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.07.22
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.07.15
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.07.01
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.06.24
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.06.17
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.06.10
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.05.27
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.05.20
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.05.13
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.05.06
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.04.29
                 </td>
 <td>
                     4
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.04.22
                 </td>
 <td>
                     4
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.04.15
                 </td>
 <td>
                     4
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.04.08
                 </td>
 <td>
                     4
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.04.01
                 </td>
 <td>
                     4
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.03.18
                 </td>
 <td>
                     5
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.03.11
                 </td>
 <td>
                     4
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.03.04
                 </td>
 <td>
                     4
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.02.25
                 </td>
 <td>
                     7
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.02.18
                 </td>
 <td>
                     7
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.02.11
                 </td>
 <td>
                     6
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.02.04
                 </td>
 <td>
                     6
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.01.28
                 </td>
 <td>
                     6
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.01.14
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2019.01.07
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.12.31
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.12.24
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.12.17
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.12.10
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.12.03
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.11.26
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.11.19
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.11.12
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.11.05
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.10.29
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.10.22
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.10.15
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.10.08
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.10.01
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.09.24
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.09.17
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.09.10
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.08.27
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.08.20
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.08.13
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.08.06
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.07.30
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.07.23
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.07.16
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.07.02
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.06.25
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.06.18
                 </td>
 <td>
                     1
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.06.11
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.05.28
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.05.21
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.05.14
                 </td>
 <td>
                     1
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.05.07
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.04.30
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.04.23
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.04.16
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.04.09
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.04.02
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.03.19
                 </td>
 <td>
                     1
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.03.05
                 </td>
 <td>
                     1
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.02.26
                 </td>
 <td>
                     1
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.02.19
                 </td>
 <td>
                     1
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.02.12
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.02.05
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.01.29
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.01.15
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.01.08
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2018.01.01
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.12.25
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.12.18
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.12.11
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.12.04
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.11.27
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.11.20
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.11.13
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.11.06
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.10.30
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.10.23
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.10.16
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.10.09
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.10.02
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.09.25
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.09.18
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.09.11
                 </td>
 <td>
                     2
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.08.28
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.08.21
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.08.14
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.08.07
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.07.31
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.07.24
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.07.17
                 </td>
 <td>
                     3
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.07.10
                 </td>
 <td>
                     5
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.07.03
                 </td>
 <td>
                     5
                 </td>
 <td>
                     0
                 </td>
 </tr>
 <tr>
 <td>
                     2017.06.26

In [6]:
soup.find('tbody').findAll('tr')[0]

<tr>
<td>
                    2019.11.11
                </td>
<td>
                    3
                </td>
<td>
                    0
                </td>
</tr>

In [4]:
data=soup.find('tbody').findAll('tr')[0].findAll('td')[0].get_text().strip()

In [5]:
ranking=soup.find('tbody').findAll('tr')[0].findAll('td')[1].get_text().strip()

In [6]:
len(soup.find('tbody').findAll('tr'))

1028

In [7]:
columns = [
    'data',
    'ranking',

]
df = pd.DataFrame(columns = columns)

In [10]:
for i in range(len(soup.find('tbody').findAll('tr'))):
    data=soup.find('tbody').findAll('tr')[i].findAll('td')[0].get_text().strip()
    ranking=soup.find('tbody').findAll('tr')[i].findAll('td')[1].get_text().strip()
   
    df = df.append({
    'data':data,
    'ranking':ranking        
    }, ignore_index=True)

In [11]:
df

            data ranking
0     2019.11.11       3
1     2019.11.04       3
2     2019.10.28       3
3     2019.10.21       3
4     2019.10.14       3
5     2019.10.07       3
6     2019.09.30       3
7     2019.09.23       3
8     2019.09.16       3
9     2019.09.09       3
10    2019.08.26       3
11    2019.08.19       3
12    2019.08.12       3
13    2019.08.05       3
14    2019.07.29       3
15    2019.07.22       3
16    2019.07.15       3
17    2019.07.01       3
18    2019.06.24       3
19    2019.06.17       3
20    2019.06.10       3
21    2019.05.27       3
22    2019.05.20       3
23    2019.05.13       3
24    2019.05.06       3
25    2019.04.29       4
26    2019.04.22       4
27    2019.04.15       4
28    2019.04.08       4
29    2019.04.01       4
...          ...     ...
998   1998.04.20    710T
999   1998.04.13    712T
1000  1998.04.06    711T
1001  1998.03.30    710T
1002  1998.03.23    707T
1003  1998.03.16    707T
1004  1998.03.09    708T
1005  1998.03.02    704T
1006  1998.02.23    705T
1007  1998.02.16    704T
1008  1998.02.09    703T
1009  1998.02.02    703T
1010  1998.01.26    706T
1011  1998.01.19    706T
1012  1998.01.12    705T
1013  1998.01.05    704T
1014  1997.12.29    704T
1015  1997.12.22    704T
1016  1997.12.15    704T
1017  1997.12.08    698T
1018  1997.12.01    699T
1019  1997.11.24    692T
1020  1997.11.17    700T
1021  1997.11.10    799T
1022  1997.11.03    802T
1023  1997.10.27    806T
1024  1997.10.20    803T
1025  1997.10.13    800T
1026  1997.10.06    799T
1027  1997.09.22    803T

[1028 rows x 2 columns]

In [12]:
df.ranking = df.ranking.str.replace('T','')
df.ranking

0         3
1         3
2         3
3         3
4         3
5         3
6         3
7         3
8         3
9         3
10        3
11        3
12        3
13        3
14        3
15        3
16        3
17        3
18        3
19        3
20        3
21        3
22        3
23        3
24        3
25        4
26        4
27        4
28        4
29        4
       ...
998     710
999     712
1000    711
1001    710
1002    707
1003    707
1004    708
1005    704
1006    705
1007    704
1008    703
1009    703
1010    706
1011    706
1012    705
1013    704
1014    704
1015    704
1016    704
1017    698
1018    699
1019    692
1020    700
1021    799
1022    802
1023    806
1024    803
1025    800
1026    799
1027    803
Name: ranking, Length: 1028, dtype: object

In [13]:
df.ranking = df.ranking.astype('int')

In [14]:
dm = df[(df['ranking']<= 5) & (df['ranking'] !=0)]

In [15]:
dm

           data  ranking
0    2019.11.11        3
1    2019.11.04        3
2    2019.10.28        3
3    2019.10.21        3
4    2019.10.14        3
5    2019.10.07        3
6    2019.09.30        3
7    2019.09.23        3
8    2019.09.16        3
9    2019.09.09        3
10   2019.08.26        3
11   2019.08.19        3
12   2019.08.12        3
13   2019.08.05        3
14   2019.07.29        3
15   2019.07.22        3
16   2019.07.15        3
17   2019.07.01        3
18   2019.06.24        3
19   2019.06.17        3
20   2019.06.10        3
21   2019.05.27        3
22   2019.05.20        3
23   2019.05.13        3
24   2019.05.06        3
25   2019.04.29        4
26   2019.04.22        4
27   2019.04.15        4
28   2019.04.08        4
29   2019.04.01        4
..          ...      ...
742  2003.09.29        3
743  2003.09.22        3
744  2003.09.15        3
745  2003.09.08        3
746  2003.08.25        2
747  2003.08.18        2
748  2003.08.11        2
749  2003.08.04        3
750  2003.07.28        3
751  2003.07.21        3
752  2003.07.14        3
753  2003.07.07        3
754  2003.06.23        5
755  2003.06.16        5
756  2003.06.09        5
757  2003.05.26        5
758  2003.05.19        5
759  2003.05.12        5
760  2003.05.05        5
761  2003.04.28        5
762  2003.04.21        5
763  2003.04.14        5
764  2003.04.07        5
765  2003.03.31        5
766  2003.03.17        4
767  2003.03.10        4
768  2003.03.03        4
769  2003.02.24        5
770  2003.02.17        5
773  2003.01.27        5

[716 rows x 2 columns]

### 2

In [8]:
# Create the link (it is a better idea to constuct the especially link if you notice a specific pattern..)
link_first_part = 'https://www.atptour.com/en/rankings/singles?rankDate=' 
link_mid_1_part = '2019-10-14'
link_mid_2_part = '&rankRange=0-10'

url = link_first_part + link_mid_1_part +link_mid_2_part
url

'https://www.atptour.com/en/rankings/singles?rankDate=2019-10-14&rankRange=0-10'

In [9]:
response =requests.get(url, timeout=50)

# parse the content with BeautifulSoup with the html.parser method
soup = BeautifulSoup(response.content, "html.parser")

#check status code of the downloaded page
response.status_code

200

In [10]:
list_date=soup.find('ul', {'class': "dropdown"} ).findAll('li')
list_date[0].get_text().strip()
list_date[0].get_text().strip().replace('.','-')

'2019-11-11'

In [11]:
lis = []
for i in range(len(list_date)):
    date = list_date[i].get_text().strip().replace('.','-')
    lis.append(date)

In [13]:
lis[0:5]

['2019-11-11', '2019-11-11', '2019-11-04', '2019-10-28', '2019-10-21']

In [19]:
url = link_first_part + lis[0] +link_mid_2_part

In [20]:
url

'https://www.atptour.com/en/rankings/singles?rankDate=2019-11-11&rankRange=0-10'

In [56]:
urls = []

for date in lis: 
    urls.append(link_first_part + date +link_mid_2_part)
urls

['https://www.atptour.com/en/rankings/singles?rankDate=2019-11-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-11-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-11-04&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-10-28&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-10-21&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-10-14&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-10-07&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-09-30&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-09-23&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-09-16&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-09-09&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-08-26&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-08-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-08-12&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-08-05&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-07-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-07-22&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-07-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-07-01&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-06-24&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-06-17&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-06-10&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-05-27&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-05-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-05-13&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-05-06&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-04-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-04-22&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-04-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-04-08&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-04-01&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-03-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-03-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-03-04&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-02-25&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-02-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-02-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-02-04&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-01-28&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-01-14&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2019-01-07&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-12-31&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-12-24&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-12-17&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-12-10&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-12-03&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-11-26&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-11-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-11-12&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-11-05&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-10-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-10-22&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-10-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-10-08&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-10-01&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-09-24&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-09-17&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-09-10&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-08-27&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-08-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-08-13&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-08-06&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-07-30&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-07-23&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-07-16&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-07-02&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-06-25&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-06-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-06-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-05-28&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-05-21&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-05-14&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-05-07&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-04-30&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-04-23&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-04-16&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-04-09&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-04-02&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-03-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-03-05&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-02-26&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-02-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-02-12&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-02-05&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-01-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-01-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-01-08&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2018-01-01&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-12-25&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-12-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-12-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-12-04&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-11-27&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-11-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-11-13&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-11-06&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-10-30&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-10-23&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-10-16&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-10-09&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-10-02&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-09-25&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-09-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-09-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-08-28&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-08-21&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-08-14&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-08-07&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-07-31&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-07-24&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-07-17&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-07-10&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-07-03&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-06-26&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-06-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-06-12&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-05-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-05-22&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-05-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-05-08&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-05-01&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-04-24&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-04-17&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-04-10&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-04-03&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-03-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-03-06&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-02-27&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-02-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-02-13&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-02-06&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-01-30&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-01-16&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-01-09&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2017-01-02&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-12-26&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-12-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-12-12&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-12-05&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-11-28&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-11-21&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-11-14&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-11-07&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-10-31&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-10-24&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-10-17&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-10-10&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-10-03&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-09-26&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-09-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-09-12&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-08-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-08-22&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-08-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-08-08&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-08-01&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-07-25&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-07-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-07-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-06-27&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-06-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-06-13&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-06-06&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-05-23&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-05-16&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-05-09&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-05-02&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-04-25&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-04-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-04-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-04-04&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-03-21&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-03-07&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-02-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-02-22&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-02-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-02-08&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-02-01&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-01-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-01-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2016-01-04&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-12-28&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-12-21&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-12-14&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-12-07&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-11-30&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-11-23&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-11-16&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-11-09&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-11-02&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-10-26&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-10-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-10-12&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-10-05&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-09-28&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-09-21&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-09-14&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-08-31&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-08-24&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-08-17&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-08-10&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-08-03&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-07-27&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-07-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-07-13&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-06-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-06-22&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-06-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-06-08&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-05-25&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-05-18&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-05-11&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-05-04&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-04-27&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-04-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-04-13&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-04-06&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-03-23&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-03-09&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-03-02&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-02-23&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-02-16&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-02-09&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-02-02&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-01-19&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-01-12&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2015-01-05&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-12-29&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-12-22&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-12-15&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-12-08&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-12-01&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-11-24&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-11-17&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-11-10&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-11-03&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-10-27&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-10-20&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-10-13&rankRange=0-10',
 'https://www.atptour.com/en/rankings/singles?rankDate=2014-10-06&rankRange=0-10',

In [58]:
response = requests.get(url, timeout=50)
soup = BeautifulSoup(response.content, "html.parser")

In [59]:
list_date=soup.find('ul', {'class': "dropdown"} ).find('li').get_text().strip()

In [60]:
columns = [
    'Date',

]
df = pd.DataFrame(columns = columns)

In [61]:
df

Empty DataFrame
Columns: [Date]
Index: []

In [64]:
from tqdm import tqdm_notebook as tqdm

In [65]:
for url in tqdm(urls): 
    response = requests.get(url, timeout=50)
    soup = BeautifulSoup(response.content, "html.parser")
    
    # use the try & except functions on cases you expect missing data
    # if the code breaks we assign the variable with np.nan or 0 or ""
    
    try:
        list_date=soup.find('ul', {'class': "dropdown"} ).find('li').get_text().strip()
    except:
        list_date = np.nan

HBox(children=(IntProgress(value=0, max=2094), HTML(value='')))

In [37]:
date

'2019-10-21'

In [48]:
df = df.append({
'Date':list_date,
}, ignore_index=True)
# before the end of the loop we introduce a time delay to respect others that want to access the website
time.sleep(0.6)

In [49]:
url

'https://www.atptour.com/en/rankings/singles?rankDate=2019-10-21&rankRange=0-10'

In [55]:
df

Empty DataFrame
Columns: [Date]
Index: []